src/views/modals/settings-content.php
www/assessment/assess/index.php
www/assessment/items/itemsapi_accessibility.php
www/assessment/items/itemsapi_assess.php
www/assessment/items/itemsapi_sections.php
www/casestudies/items/xapi/index.php

[Polish] Update accessibility examples to reflect latest schema

---

README.md

Reverts Learnosity/learnosity-demos#7

Revert "Add a Gitter badge to the README"

---

src/includes/nav.php
www/casestudies/items/endtoend/assessment.php
www/casestudies/items/endtoend/authoring.php
www/casestudies/items/endtoend/endpoint.php
www/casestudies/items/endtoend/feedback.php
www/casestudies/items/endtoend/feedback_report.php
www/casestudies/items/endtoend/index.php

@mcgoughn could you please review the end to end demo?
Thanks,

Endtoend demo

---

www/config.php
www/xhr.php

This is needed if testing against an self-signed certificate server

[UPDATE] added the ability to turn off SSL verification

---

www/static/css/main.css

[POLISH] Remove !important from the demo site

---

www/authoring/questioneditor/v3/editteacherclozedd.php
www/authoring/questioneditor/v3/editteacherequation.php
www/authoring/questioneditor/v3/editteachermcq.php

Polish on teacher authoring demo

Teacherauthoring

---

www/assessment/items/index.php
www/assessment/items/itemsapi_adaptive.php
www/assessment/items/itemsapi_adaptive_report.php
www/assessment/items/itemsapi_branching.php
www/assessment/items/itemsapi_itembranching.php

[FEATURE] Add item branching demo

---

src/views/modals/settings-content.php
src/views/modals/settings-content2.php
src/views/modals/settings-items.php

[CHANGES] reverted settings-content.php so assess/index.php modal will not break, created settings-content2.php for items/itemsapi_assess.php modal content

Fix file overlap issue

---

www/authoring/questioneditor/v3/main.php

[BUG] Scroll QE into view

---

src/views/modals/settings-content.php
www/assessment/assess/index.php

Add show_submit to list of available Assess administration options

---

src/views/modals/settings-content.php
www/assessment/assess/index.php

Reverts Learnosity/learnosity-demos#69

Revert "Add show_submit to list of available Assess administration options"

---

src/views/modals/regions-settings.php
www/assessment/items/regions_settings.js
www/assessment/items/regions_settings_style.css

https://learnosity.atlassian.net/browse/LRN-16813

[DEMOS] Refactor regions configs demo and add top region

---

www/assessment/items/index.php
www/assessment/items/itemsapi_question_indexing.php

Add question indexing demo page

---

www/authoring/questioneditor/v3/assetrequest.php
www/authoring/questioneditor/v3/index.php

Qe v3 demos cleanup

---

Makefile

[TESTS] add lint task for php syntax check

---

src/includes/nav.php

Signed-off-by: Olivier Mehani <olivier.mehani@learnosity.com>

[BUG][PHP7] remove deprecated each

---

www/assessment/testlet-adaptive.php

@walsh-conor I migrated the activities and added the read-only org_id, everything seems to be working but you're more familiar with this demo than I am, would you mind having a look and merging if you think it's good to go?

Add org_id to testlet-adaptive demo

---

www/lrn_config.php
www/usecases/index.php
www/usecases/single-page-app.php

This change adds a single page app example to illustrate best practices for managing the lifecycle of Items API instances.

Add single page app assessment demo

---

www/usecases/index.php
www/usecases/single-page-app.php

This change:
* Adds a link to the companion KB article.
* Updates the description content in line with the KB article.
* Adds and improves code comments and code organisation.

[DOC] Improve single page app demo description and code comments

---

www/authoring/index.php
www/authoring/workflow.php

[FEATURE] Add workflow demo

---

www/authoring/custom-ckeditor-toolbar.php

Info 233/edit text for ckeditor toolbar customization demo

Fix graphics for mobile users in ckeditor customization demo

---

www/assessment/customization/style-guide/index.php
www/assessment/customization/style-guide/package.json
www/assessment/customization/style-guide/src/App.js
www/assessment/customization/style-guide/src/assets/scss/app.scss
www/assessment/customization/style-guide/src/components/QuestionContainer.js
www/assessment/customization/style-guide/src/config.json
www/assessment/customization/style-guide/src/contants/index.js
www/assessment/customization/style-guide/src/contants/selectors.js
www/assessment/customization/style-guide/src/ducks/appConfig.js
www/assessment/customization/style-guide/src/ducks/questionApi.js
www/assessment/customization/style-guide/src/index.js
www/assessment/customization/style-guide/src/services/questionApiService.js
www/assessment/customization/style-guide/src/store.js
www/assessment/customization/style-guide/yarn.lock

JIRA :  https://learnosity.atlassian.net/browse/LRN-34259
- Setup the boilerplate for ReactJS 
- Setup the store state management with Redux
- Integrate Learnosity SDK API
- Load the JSON config and populate it to store
- Append the widget
- Render the widget to the UI

[FEATURE] GCA - setup ReactJS + Redux with Learnosity API integration - LRN-34259

---

www/usecases/customquestions/custom_box_whisker.php
www/usecases/customquestions/custom_percentage_bar.php
www/usecases/customquestions/index.php
www/usecases/index.php

Signed-off-by: Olivier Mehani <olivier.mehani@learnosity.com>

Random fixes LRN-35627

---

www/partners/alchemie.php
www/partners/brainingcamp.php
www/partners/index.php

Add new tech partners demos:
- Braningcamp demo
- Alchemie demo

[FEATURE] Add new partners demos

---

www/authoring/custom-qe-layout.php

[BUG] Fix options path for mcq custom layout

---

src/utils/settings-override.php
www/assessment/distractor-rationale.php

@kent-nguyen-lrn 
In reviewing the demos for errors using PHP8.1 in preparation for the upgrade, I found and fixed a couple in assessment, and the PR here is for that fix.
You can see the errors fixed on the [Upgrade Test Tracker here](https://docs.google.com/spreadsheets/d/14mopqfh27v0cc-cazHMV3clB7CiHI0jE_aqUdS5G5q4/edit#gid=1461025844).
If you have any questions or I can clarify anything please feel free to let me know! And thank you in advance!

[FIX] assessment errors for php8.1 upgrade

---

www/lrn_config.php

Pointed demos to v2023.1.LTS as Nina requested.
I've done some testing and can see it works on my side.
Please feel free to test, and merge once all clear.

[FIX] Point demos to v2023.1.LTS version.

---

www/analytics/group-reporting.php
www/analytics/index.php
www/analytics/no-ui-reports.php
www/analytics/outcomes-mastery-reporting.php
www/analytics/progress-centric-reporting.php
www/analytics/reports-click-events-modal.php
www/analytics/student-centric-reporting.php
www/analytics/teacher-centric-reporting.php

Update reports name to keep consistency 
Based in :
https://docs.google.com/spreadsheets/d/1AB6EjxfYAWrn_hn_xF4LKhYtq8aCEvWZT8hon5ydlyI/edit#gid=0

[BUG] Update reports name to keep consistency LRN-40173

---

www/analytics/reports-click-events.php
www/assessment/distractor-rationale.php
www/assessment/distractors.php
www/assessment/events.php
www/assessment/reset-response.php
www/assessment/rtl.php
www/authoring/events.php
www/authoring/item-list-enable-selection.php
www/authoring/question-edit.php
www/authoring/routing.php
www/authoring/rtl.php
www/authoring/workflow.php
www/usecases/single-page-app.php

Updates for links to the new Reference Site content, because the URLs and hierarchy have changed. Based on this ticket report from Brad Hunt: https://learnosity.atlassian.net/browse/INFO-712

[DOC] Update links out to the Reference Site.

---

package-lock.json
www/authoring/index.php
www/authoring/random-activity-create.php
www/lrn_config.php

[FEATURE] add random assessment demo LRN-24839

---

www/analytics/data/index.php
www/analytics/data/xhr.php

Improve validation of endpoints in demo site

[CLEANUP] Improve validation of endpoints in demo site

---

www/assessment/stem-assessment.php

This is updating the description of the STEM Assessment demo to inform the availability of a premium feature called Math Image Capture.

Update STEM Assessment demo with Math Image Capture LRN-44941

---

www/lrn_config.php
www/usecases/feedback/manual-grading-inline/grading.php
www/usecases/feedback/manual-grading-inline/includes/js/grading.js
www/usecases/feedback/manual-grading-inline/includes/styles/main.css
www/usecases/feedback/manual-grading-inline/index.php
www/usecases/feedback/manual-grading-inline/report.php

JIRA: [LRN-45244](https://learnosity.atlassian.net/browse/LRN-45244)
- This is for the Manual grading inline production demo. This will use the activity template of "Manual grading collection" for the content that's link to the org-id 505. The next 2 page will not work at the moment since the grading-api requires the postgressDB so for now we only focus with showing the first page.
[LRN-45244]: https://learnosity.atlassian.net/browse/LRN-45244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEMO] Manual grading inline production demo - LRN-45244

---

www/usecases/feedback/manual-grading-inline/grading.php
www/usecases/feedback/manual-grading-inline/index.php
www/usecases/feedback/manual-grading-inline/report.php

- FIx the issue in MANGA authentication in grading.php

[TEST] - fix the security authentication by adding org_id of 505  - LRN-45244

---

www/usecases/feedback/manual-grading-inline/grading.php
www/usecases/feedback/manual-grading-inline/includes/js/grading.js
www/usecases/feedback/manual-grading-inline/includes/styles/main.css
www/usecases/feedback/manual-grading-inline/index.php
www/usecases/feedback/manual-grading-inline/report.php

- This is the fix for the Manual Grading's issue regarding the items aren't loading becz of incompatible org ID

[TEST] Fix the issue with the items by adding the org ID - LRN-45244

---

www/usecases/feedback/manual-grading-inline/grading.php
www/usecases/feedback/manual-grading-inline/includes/js/grading.js
www/usecases/feedback/manual-grading-inline/includes/js/items.js
www/usecases/feedback/manual-grading-inline/includes/styles/main.css
www/usecases/feedback/manual-grading-inline/index.php
www/usecases/feedback/manual-grading-inline/report.php

- FIx the issue in the feedback not picking the updates
- Fix the UI styles
- Refactoring with CSS and  grading + items JS

[TEST] Fix the issue in feedback in reports and styles adjustments - LRN-45244

---

www/usecases/feedback/manual-grading-inline/grading.php
www/usecases/feedback/manual-grading-inline/includes/js/grading.js
www/usecases/feedback/manual-grading-inline/includes/styles/main.css
www/usecases/feedback/manual-grading-inline/report.php

- Change the grading report title. 
- Disable the button when the save is busy in page 2. 
- Add spinner animation on the button submit when busy

[TEST] Change the grading report title. Update UI per design review - LRN-45244

---

www/usecases/feedback/manual-grading-inline/includes/styles/main.css

- adjusted the assess player in page 1

[TEST] Manga demo, adjustment for assessment player in page-1 - 244

---

www/usecases/feedback/manual-grading-inline/includes/js/items.js
www/usecases/feedback/manual-grading-inline/includes/styles/main.css
www/usecases/index.php

- Add Manual grading inline panel on the first page
- Remove the CSS workaround

[TEST] Manga demo fixes and refinements - LRN-45244

---

www/usecases/feedback/manual-grading-inline/grading.php
www/usecases/feedback/manual-grading-inline/index.php
www/usecases/feedback/manual-grading-inline/report.php
www/usecases/index.php

JIRA: LRN-45244
- update the Manual grading inline panel

[TEST] Manga demo update the Manual grading inline panel text content - LRN-45244

---

www/usecases/feedback/manual-grading-inline/grading.php
www/usecases/feedback/manual-grading-inline/index.php
www/usecases/feedback/manual-grading-inline/report.php

- Update the demo links in every manual grading inline demo pages

[DEMO] Update the docs link in Manual Grading demo page - LRN-45244

---

www/authoring/question_templates.php

Replace old CloudFront URL with assets.learnosity.com URL for image resources.

Swap CloudFront URL to assets.learnosity.com

---

src/includes/footer.php
src/includes/nav.php
www/index.php

* [BUG] Hide view source button for pages that don't have it INFO-1327

[DOC] Update homepage content and view source button

---

www/lrn_config.php

Changed lrn_config.php to have v2025.2.LTS.

[UPGRADE]Upgrade LTS version to v2025.2.LTS

---

src/views/modals/settings-content-author.php
www/authoring/hide-tags.php
www/authoring/item-edit-simple.php
www/authoring/item-list-browse-tag-hierarchy.php
www/authoring/item-list-enable-selection.php
www/authoring/item-list-filtered.php

[BUG] Use object for duplicate init option
